server:
  port: 6060

spring:
  application:
    name: blogic
  webflux:
    basePath: /blogic
  messages:
    basename: codedException,changeRecord
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/blogic?serverZoneId=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: ${MYSQL_PASSWORD:}
    name: r2dbc
    pool:
      validation-query: SELECT 1
      enabled: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS}|%-5level|%X{traceId}|%X{spanId}|${spring.application.name}|%t|%C|%m%n'
  level:
    root: info
    blogic: debug
    blogic.core: info
    org.springframework.r2dbc: debug

blogic:
  jwt:
    key: 123456
  errorMessageHandle: false
  permitUrls:
    - POST:/blogic/login
    - POST:/blogic/Users
